---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21759", "ManageIQ/manageiq-providers-amazon#746",
        "ManageIQ/manageiq-providers-openstack#784", "ManageIQ/manageiq-providers-ibm_cloud#349",
        "ManageIQ/manageiq-ui-classic", "ManageIQ/manageiq-api"]'
      repos: ManageIQ/manageiq#21759,ManageIQ/manageiq-providers-amazon#746,ManageIQ/manageiq-providers-openstack#784,ManageIQ/manageiq-providers-ibm_cloud#349,ManageIQ/manageiq-ui-classic,ManageIQ/manageiq-api
