---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21778", "ManageIQ/manageiq-api", "ManageIQ/manageiq-providers-ibm_cloud#357",
        "ManageIQ/manageiq-providers-ibm_power_vc#51", "ManageIQ/manageiq-providers-lenovo#363",
        "ManageIQ/manageiq-ui-classic#8177"]'
      repos: ManageIQ/manageiq#21778,ManageIQ/manageiq-providers-ibm_cloud#357,ManageIQ/manageiq-providers-ibm_power_vc#51,ManageIQ/manageiq-providers-lenovo#363,ManageIQ/manageiq-ui-classic#8177
