---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22680", "ManageIQ/manageiq-automation_engine#532",
        "ManageIQ/manageiq-content#737"]'
      repos: ManageIQ/manageiq#22680,ManageIQ/manageiq-automation_engine#532,ManageIQ/manageiq-content#737
