---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22239", "ManageIQ/manageiq-api#1186", "ManageIQ/manageiq-providers-ovirt#621",
        "ManageIQ/manageiq-providers-red_hat_virtualization#17", "ManageIQ/manageiq-schema#672",
        "ManageIQ/manageiq-ui-classic#8548"]'
      repos: ManageIQ/manageiq#22239,ManageIQ/manageiq-api#1186,ManageIQ/manageiq-providers-ovirt#621,ManageIQ/manageiq-providers-red_hat_virtualization#17,ManageIQ/manageiq-schema#672,ManageIQ/manageiq-ui-classic#8548
