---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22688", "ManageIQ/manageiq-providers-kubernetes",
        "ManageIQ/manageiq-providers-openshift"]'
      repos: ManageIQ/manageiq#22688
