---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22269", "ManageIQ/manageiq-providers-kubernetes#479",
        "ManageIQ/manageiq-providers-vmware#841", "ManageIQ/manageiq-providers-openstack#832",
        "ManageIQ/manageiq-providers-nuage#283"]'
      repos: ManageIQ/manageiq#22269,ManageIQ/manageiq-providers-kubernetes#479,ManageIQ/manageiq-providers-vmware#841,ManageIQ/manageiq-providers-openstack#832,ManageIQ/manageiq-providers-nuage#283
