---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21828", "ManageIQ/manageiq-providers-kubernetes#463",
        "ManageIQ/manageiq-providers-openshift#224"]'
      repos: ManageIQ/manageiq#21828,ManageIQ/manageiq-providers-kubernetes#463,ManageIQ/manageiq-providers-openshift#224
