---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/ManageIQ#23142", "ManageIQ/manageiq#23142"]'
      repos: ManageIQ/ManageIQ#23142,ManageIQ/manageiq#23142,ManageIQ/manageiq-providers-ovirt#676,ManageIQ/manageiq-providers-red_hat_virtualization#54
