---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22293"]'
      repos: ManageIQ/manageiq#22293,ManageIQ/manageiq-automation_engine#516,ManageIQ/manageiq-schema#681,ManageIQ/manageiq-ui-classic#8400
