---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-autosde#139/files", "ManageIQ/manageiq-ui-classic#8161"]'
      repos: ManageIQ/manageiq-providers-autosde#139/files,ManageIQ/manageiq-ui-classic#8161
