---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-api#1164", "ManageIQ/manageiq-ui-classic#8301"]'
      repos: ManageIQ/manageiq-api#1164,ManageIQ/manageiq-ui-classic#8301
