---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22570", "ManageIQ/manageiq-api", "ManageIQ/manageiq-providers-ansible_tower",
        "ManageIQ/manageiq-providers-awx", "ManageIQ/manageiq-providers-workflows",
        "ManageIQ/manageiq-ui-classic"]'
      repos: ManageIQ/manageiq#22570,ManageIQ/manageiq-providers-workflows#30
