---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["agrare/manageiq@najdorf_add_cisco_intersight_provider", "agrare/manageiq-providers-cisco_intersight@najdorf"]'
      repos: agrare/manageiq@najdorf_add_cisco_intersight_provider,agrare/manageiq-providers-cisco_intersight@najdorf
