---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-workflows#63"]'
      repos: ManageIQ/floe#152,ManageIQ/manageiq-providers-workflows#63
