---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/inventory_refresh#115", "ManageIQ/manageiq-providers-vmware#844"]'
      repos: ManageIQ/inventory_refresh#115,ManageIQ/manageiq-providers-vmware#844
