---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21964", "ManageIQ/manageiq-api", "ManageIQ/manageiq-providers-openshift#227",
        "ManageIQ/manageiq-ui-classic"]'
      repos: ManageIQ/manageiq#21964,ManageIQ/manageiq-providers-openshift#227
