---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-ibm_cic#31", "ManageIQ/manageiq-providers-openstack#840"]'
      repos: ManageIQ/manageiq-providers-ibm_cic#31,ManageIQ/manageiq-providers-openstack#840
