---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/floe#44", "ManageIQ/manageiq#22316", "ManageIQ/manageiq-providers-workflows#5"]'
      repos: ManageIQ/floe#44,ManageIQ/manageiq#22316,ManageIQ/manageiq-providers-workflows#5
