---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21698", "ManageIQ/manageiq-api", "ManageIQ/manageiq-providers-ovirt#595", "ManageIQ/manageiq-ui-classic#8116", "ManageIQ/manageiq-providers-red_hat_virtualization#6"]'
      repos: ManageIQ/manageiq#21698,ManageIQ/manageiq-providers-ovirt#595,ManageIQ/manageiq-ui-classic#8116,ManageIQ/manageiq-providers-red_hat_virtualization#6
