---
name: Cross Repo Tests
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/inventory_refresh@master", "ManageIQ/manageiq#21680"]'
      repos: ManageIQ/inventory_refresh@master,ManageIQ/manageiq#21680
