---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23590", "ManageIQ/manageiq-api#1299", "ManageIQ/manageiq-providers-openstack#920",
        "ManageIQ/manageiq-providers-ovirt#696"]'
      repos: ManageIQ/manageiq#23590,ManageIQ/manageiq-api#1299,ManageIQ/manageiq-providers-openstack#920,ManageIQ/manageiq-providers-ovirt#696
