---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22234", "ManageIQ/manageiq-providers-vmware#837"]'
      repos: ManageIQ/manageiq#22234,ManageIQ/manageiq-providers-vmware#837
