---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-vmware", "ManageIQ/vmware_web_service#132"]'
      repos: ManageIQ/vmware_web_service#132
