---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-kubevirt#265", "ManageIQ/manageiq-providers-openshift#276"]'
      repos: ManageIQ/manageiq-providers-kubevirt#265,ManageIQ/manageiq-providers-openshift#276
