---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21698", "ManageIQ/manageiq-providers-ovirt#595",
        "ManageIQ/manageiq-providers-red_hat_virtualization", "ManageIQ/manageiq-ui-classic#8116"]'
      repos: ManageIQ/manageiq#21698,ManageIQ/manageiq-providers-ovirt#595,ManageIQ/manageiq-ui-classic#8116
