---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-ui-classic@39db7325d71e24fb5fa40805238dbc351169ba42"]'
      repos: ManageIQ/manageiq@34e4f883967abdcd8ad35ce40161c760074ad747
