---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22336", "ManageIQ/manageiq-api#1202", "ManageIQ/manageiq-providers-openstack#839",
        "ManageIQ/manageiq-providers-vmware#859"]'
      repos: ManageIQ/manageiq#22336,ManageIQ/manageiq-api#1202,ManageIQ/manageiq-providers-openstack#839,ManageIQ/manageiq-providers-vmware#859
