---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-ibm_cloud#474", "ManageIQ/manageiq-providers-ibm_power_hmc#147",
        "ManageIQ/manageiq-schema#708"]'
      repos: ManageIQ/manageiq-providers-ibm_cloud#474,ManageIQ/manageiq-providers-ibm_power_hmc#147,ManageIQ/manageiq-schema#708
