---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23308", "ManageIQ/manageiq-providers-embedded_terraform#79"]'
      repos: ManageIQ/manageiq#23308,ManageIQ/manageiq-providers-embedded_terraform#79
