---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23145", "ManageIQ/manageiq-schema#745"]'
      repos: ManageIQ/manageiq#23145,ManageIQ/manageiq-schema#745
