---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21807", "ManageIQ/manageiq-providers-ibm_cloud#363",
        "ManageIQ/manageiq-schema#644"]'
      repos: ManageIQ/manageiq#21807,ManageIQ/manageiq-providers-ibm_cloud#363,ManageIQ/manageiq-schema#644
