---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-gems-pending#558", "ManageIQ/manageiq-providers-openstack#734"]'
      repos: ManageIQ/manageiq-gems-pending#558,ManageIQ/manageiq-providers-openstack#734
