---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23037", "ManageIQ/manageiq-api", "ManageIQ/manageiq-automation_engine",
        "ManageIQ/manageiq-content", "ManageIQ/manageiq-ui-classic"]'
      repos: ManageIQ/manageiq#23037
