---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: agrare/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@refactor_cross_repo_runner
    with:
      test-repos: '["agrare/manageiq-providers-vmware@ruby3"]'
      repos: ManageIQ/manageiq#21531
