---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22316", "ManageIQ/manageiq-schema#679", "ManageIQ/manageiq-api#1214", "ManageIQ/manageiq-providers-workflows#6"]'
      repos: ManageIQ/manageiq#22316,ManageIQ/manageiq-schema#679,ManageIQ/manageiq-api#1214,ManageIQ/manageiq-providers-workflows#6
