---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: agrare/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@remove_bundle_path
    with:
      test-repos: '["ManageIQ/manageiq@master", "ManageIQ/manageiq-ui-classic#8373"]'
      repos: ManageIQ/manageiq@master,ManageIQ/manageiq-ui-classic#8373
