---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22801", "ManageIQ/manageiq-api#1243", "ManageIQ/manageiq-automation_engine#537"]'
      repos: ManageIQ/manageiq#22801,ManageIQ/manageiq-api#1243,ManageIQ/manageiq-automation_engine#537
