---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21841", "ManageIQ/manageiq-api#1156", "ManageIQ/manageiq-providers-amazon#767",
        "ManageIQ/manageiq-providers-ibm_cloud#373", "ManageIQ/manageiq-providers-openstack#794",
        "ManageIQ/manageiq-ui-classic#8247"]'
      repos: ManageIQ/manageiq#21841,ManageIQ/manageiq-api#1156,ManageIQ/manageiq-providers-amazon#767,ManageIQ/manageiq-providers-ibm_cloud#373,ManageIQ/manageiq-providers-openstack#794,ManageIQ/manageiq-ui-classic#8247
