---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23261", "ManageIQ/manageiq-api", "ManageIQ/manageiq-automation_engine#562",
        "ManageIQ/manageiq-consumption", "ManageIQ/manageiq-content", "ManageIQ/manageiq-decorators",
        "ManageIQ/manageiq-gems-pending#596", "ManageIQ/manageiq-providers-amazon",
        "ManageIQ/manageiq-providers-ansible_tower", "ManageIQ/manageiq-providers-autosde",
        "ManageIQ/manageiq-providers-awx", "ManageIQ/manageiq-providers-azure", "ManageIQ/manageiq-providers-azure_stack",
        "ManageIQ/manageiq-providers-cisco_intersight", "ManageIQ/manageiq-providers-embedded_terraform",
        "ManageIQ/manageiq-providers-foreman", "ManageIQ/manageiq-providers-google",
        "ManageIQ/manageiq-providers-ibm_cic", "ManageIQ/manageiq-providers-ibm_cloud",
        "ManageIQ/manageiq-providers-ibm_power_hmc", "ManageIQ/manageiq-providers-ibm_power_vc",
        "ManageIQ/manageiq-providers-ibm_terraform", "ManageIQ/manageiq-providers-kubernetes",
        "ManageIQ/manageiq-providers-kubevirt", "ManageIQ/manageiq-providers-lenovo",
        "ManageIQ/manageiq-providers-nsxt", "ManageIQ/manageiq-providers-nuage", "ManageIQ/manageiq-providers-openshift",
        "ManageIQ/manageiq-providers-openstack", "ManageIQ/manageiq-providers-oracle_cloud",
        "ManageIQ/manageiq-providers-ovirt#680", "ManageIQ/manageiq-providers-red_hat_virtualization",
        "ManageIQ/manageiq-providers-redfish", "ManageIQ/manageiq-providers-vmware#926",
        "ManageIQ/manageiq-providers-workflows", "ManageIQ/manageiq-schema", "ManageIQ/manageiq-ui-classic#9307",
        "ManageIQ/manageiq-ui-service", "ManageIQ/vmware_web_service#141"]'
      repos: ManageIQ/manageiq#23261,ManageIQ/vmware_web_service#141
