---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22698", "ManageIQ/manageiq-automation_engine#538",
        "ManageIQ/manageiq-providers-vmware#892"]'
      repos: ManageIQ/manageiq#22698,ManageIQ/manageiq-automation_engine#538,ManageIQ/manageiq-providers-vmware#892
