---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    strategy:
      fail-fast: false
      matrix:
        test-suite:
        - spec
        - spec:compile
        - spec:javascript
        - spec:jest
        - spec:routes
        - spec:security
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-lenovo#443", "ManageIQ/manageiq-providers-nsxt#167",
        "ManageIQ/manageiq-ui-classic#9799"]'
      repos: ManageIQ/manageiq-providers-lenovo#443,ManageIQ/manageiq-providers-nsxt#167,ManageIQ/manageiq-ui-classic#9799
      test-suite: ${{ matrix.test-suite }}
