---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22271", "ManageIQ/manageiq-providers-nuage#281",
        "ManageIQ/manageiq-providers-openstack#830"]'
      repos: ManageIQ/manageiq#22271,ManageIQ/manageiq-providers-nuage#281,ManageIQ/manageiq-providers-openstack#830
