---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#22274", "ManageIQ/manageiq-api#1190"]'
      repos: ManageIQ/manageiq#22274,ManageIQ/manageiq-api#1190
