---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21650", "ManageIQ/manageiq-providers-amazon",
        "ManageIQ/manageiq-providers-ansible_tower", "ManageIQ/manageiq-providers-autosde",
        "ManageIQ/manageiq-providers-azure", "ManageIQ/manageiq-providers-azure_stack",
        "ManageIQ/manageiq-providers-cisco_intersight", "ManageIQ/manageiq-providers-foreman#103",
        "ManageIQ/manageiq-providers-google", "ManageIQ/manageiq-providers-ibm_cic",
        "ManageIQ/manageiq-providers-ibm_cloud", "ManageIQ/manageiq-providers-ibm_power_hmc",
        "ManageIQ/manageiq-providers-ibm_power_vc", "ManageIQ/manageiq-providers-ibm_terraform",
        "ManageIQ/manageiq-providers-kubernetes", "ManageIQ/manageiq-providers-kubevirt",
        "ManageIQ/manageiq-providers-lenovo", "ManageIQ/manageiq-providers-nsxt",
        "ManageIQ/manageiq-providers-nuage", "ManageIQ/manageiq-providers-openshift",
        "ManageIQ/manageiq-providers-openstack#801", "ManageIQ/manageiq-providers-oracle_cloud",
        "ManageIQ/manageiq-providers-ovirt", "ManageIQ/manageiq-providers-redfish",
        "ManageIQ/manageiq-providers-scvmm", "ManageIQ/manageiq-providers-vmware"]'
      repos: ManageIQ/manageiq#21650,ManageIQ/manageiq-providers-foreman#103,ManageIQ/manageiq-providers-openstack#801
