---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21818", "ManageIQ/manageiq-providers-cisco_intersight#40",
        "ManageIQ/manageiq-providers-lenovo#366"]'
      repos: ManageIQ/manageiq#21818,ManageIQ/manageiq-providers-cisco_intersight#40,ManageIQ/manageiq-providers-lenovo#366
