---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#21847", "ManageIQ/manageiq-providers-openstack#798",
        "ManageIQ/manageiq-providers-ovirt#600", "ManageIQ/manageiq-providers-vmware#804"]'
      repos: ManageIQ/manageiq#21847,ManageIQ/manageiq-providers-openstack#798,ManageIQ/manageiq-providers-ovirt#600,ManageIQ/manageiq-providers-vmware#804
