---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23014", "ManageIQ/manageiq-providers-amazon#854",
        "ManageIQ/manageiq-schema#733", "ManageIQ/manageiq-ssh-util@master"]'
      repos: ManageIQ/manageiq#23014,ManageIQ/manageiq-providers-amazon#854,ManageIQ/manageiq-schema#733,ManageIQ/manageiq-ssh-util@master
