---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-providers-ansible_tower#301", "ManageIQ/manageiq-providers-awx#22",
        "ManageIQ/manageiq-schema#714"]'
      repos: ManageIQ/manageiq-providers-ansible_tower#301,ManageIQ/manageiq-providers-awx#22,ManageIQ/manageiq-schema#714
