---
name: Cross Repo

on:
- pull_request

jobs:
  cross-repo:
    uses: agrare/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@bump_bundler_2_3_20
    with:
      test-repos: '["ManageIQ/manageiq-ui-classic@master"]'
      repos: ManageIQ/manageiq#22040
