---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23244", "ManageIQ/manageiq-api#1273", "ManageIQ/manageiq-schema#764",
        "ManageIQ/manageiq-ui-classic#9303"]'
      repos: ManageIQ/manageiq#23244,ManageIQ/manageiq-api#1273,ManageIQ/manageiq-schema#764,ManageIQ/manageiq-ui-classic#9303
