---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq#23165", "ManageIQ/manageiq-providers-kubernetes#537",
        "ManageIQ/manageiq-providers-kubevirt#247", "ManageIQ/manageiq-providers-openshift#264"]'
      repos: ManageIQ/manageiq#23165,ManageIQ/manageiq-providers-kubernetes#537,ManageIQ/manageiq-providers-kubevirt#247,ManageIQ/manageiq-providers-openshift#264
