---
name: Cross Repo
on:
- pull_request
jobs:
  cross-repo:
    uses: ManageIQ/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@master
    with:
      test-repos: '["ManageIQ/manageiq-api#1163", "ManageIQ/manageiq-providers-autosde#150",
        "ManageIQ/manageiq-ui-classic#8279"]'
      repos: ManageIQ/manageiq-api#1163,ManageIQ/manageiq-providers-autosde#150,ManageIQ/manageiq-ui-classic#8279
