---
name: Close PRs

on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "ruby"
      timeout-minutes: 30
    - name: Close PRs
      env:
        GITHUB_API_TOKEN: "${{ secrets.PR_TOKEN }}"
      run: bin/close_prs
